### ISSUE TITLE
Tool crashing while opening 

### ISSUE THREAD

**Issue by carfup** [Power-Maverick/PCF-CustomControlBuilder#14]
**Describe the bug**
When opening the Tool from XrmToolBox, i just get an exception : 

System.ArgumentOutOfRangeException: La longueur ne peut pas être inférieure à zéro.
Nom du paramètre : length
   à System.String.Substring(Int32 startIndex, Int32 length)
   à Maverick.PCF.Builder.MainPluginControl.CheckPacVersion()
   à Maverick.PCF.Builder.MainPluginControl.MainPluginControl_Load(Object sender, EventArgs e)
   à System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.Form.WmShowWindow(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

and the entire XrmToolBox crashed as well. 

Maybe it's specifically related to my XTB instance, but maybe you also know what to do !
I tried to uninstall and reinstall the tool, same result.

**To Reproduce**
1. open the Tool from the Tool list

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Win10
 - XrmToolbox Version : 1.2019.11.35
 - PCF Custom Control Builder Version : 2.2019.10.22

Thanks a lot !

**Comment by Power-Maverick** [comment]
Can you update the tool and let me know if you still face this issue? It's hard cause I am unable to replicate it.

**Comment by carfup** [comment]
Awesome, the update indeed fixed it.

Thanks a lot !
