### ISSUE TITLE
Terminate Running Process explodes if nothing is running

### ISSUE THREAD

**Issue by rappen** [Power-Maverick/PCF-CustomControlBuilder#15]
![PCCB Terminate Crash](https://user-images.githubusercontent.com/2572253/71178317-3938eb80-226e-11ea-83a9-024b05e1dbfd.gif)

**Comment by Power-Maverick** [comment]
Hi Jonas, It has been difficult to re-create the scenario. But I think I have handled it by making the button disabled on load. I will need help testing it so will send you the updated assembly.

**Comment by Power-Maverick** [comment]
This should be fixed in 2.2020.02.03 release
