### ISSUE TITLE
Plugin should not assume code file is called index.ts

### ISSUE THREAD

**Issue by eleung83** [Power-Maverick/PCF-CustomControlBuilder#16]
First of all this plugin saves me the hassle of having to manually run commands to build/deploy these solutions so kudos for that

One thing I noticed though, is the plugin assumes that the code file is called index.ts.

If the file is not called index.ts then the component/solution details do not get loaded.

The manifest file allows for any variation of filename for the code file, so it should not be hardcoded to look for index.ts. Either it should read through the manifest xml file for the code element, or allow an extra input parameter for defining the code file to check

**Comment by Power-Maverick** [comment]
Agreed. I'll get that fixed in next release. Thanks for bringing this to my notice.

**Comment by Power-Maverick** [comment]
This should be fixed in 2.2020.02.03 release. Please retest and close it out.

**Comment by eleung83** [comment]
Looks good, changed the name of the file and it managed to build it fine
