### ISSUE TITLE
first cd command now working

### ISSUE THREAD

**Issue by aboodh95** [Power-Maverick/PCF-CustomControlBuilder#17]
**Describe the bug**
I was using the tool and everything worked fine, after some updates, the tool is not acting correctly, the path of excitation is not correct (XRMToolBox path), none of the buttons are exciting correctly, the solution is not being created or deployed

**To Reproduce**
creating or loading will have the same message
![image](https://user-images.githubusercontent.com/12459798/78506640-0880b180-778c-11ea-9fec-42711a05471c.png)

**Expected behavior**
not navigating to the path of control

**Desktop (please complete the following information):**
 - OS: Win10
 - XrmToolbox Version: 1.2020.2.37
 - PCF Custom Control Builder Version: 2.2020.3.22

**Comment by PingPongLee** [comment]
I can confirm that i have the same error. It seems like its not sending a newline / enter key stroke before it begins to attempt to build resulting in the error

**Comment by Power-Maverick** [comment]
This has been resolved in the latest update. Please update the tool in XrmToolbox.
