### ISSUE TITLE
Allow Choosing an existing solution instead of filling in a new solution details

### ISSUE THREAD

**Issue by ZaarourOmar** [Power-Maverick/PCF-CustomControlBuilder#18]
When we already have a solution that contains all the controls existing in CDS, the toolbox plugin should allow us to deploy the control to an existing solution. Currently we only have the option of either creating a new solution or use the quick deployment

**Comment by Power-Maverick** [comment]
New version of tool accomplishes this idea. Download the latest version. Thanks for suggesting it.
