### ISSUE TITLE
Issue while trying to create New from template (CRM Datacard Master)

### ISSUE THREAD

**Issue by MansiRungta** [Power-Maverick/PCF-CustomControlBuilder#20]
Bug Description : When I try to create a new PCF with New from template and i choose CRM-Datacard-Master template, it doesnt get created and an error msg pops up which says report this issue in github

1. New PCF - New from template
2. Select CRM Datacard Master
3. See error

Expected behaviour : The new PCF folder should get created

 - OS: Win10
 - XrmToolbox Version : 2020.4.38
 - PCF Custom Control Builder Version : 2.2020.3.22

Screenshot:

![image](https://user-images.githubusercontent.com/64459290/81088249-03ce2b00-8efb-11ea-8f13-c67dcba216c7.png)

**Comment by Power-Maverick** [comment]
If this is the control you are talking about - https://pcf.gallery/datacard/ , then I looked at the repo and the tool's author has not created a proper repo. It should include **.pcfproj**. Hence, you are getting error. Please reach out to the tool's author to correct the repo published on GitHub.
