### ISSUE TITLE
Add the possibility to choose build configuration Debug or Release

### ISSUE THREAD

**Issue by MscrmTools** [Power-Maverick/PCF-CustomControlBuilder#25]
Hi,
I don't even know it this is something possible but would be nice to reduce bundles size

**Comment by Power-Maverick** [comment]
It already exists in the current version. See below.
![image](https://user-images.githubusercontent.com/36135520/88978965-b14ca280-d28e-11ea-9b41-b0d1b75a225d.png)

**Comment by MscrmTools** [comment]
Good to know! What if I want to generate both managed and unmanaged solution with release configuration?

**Comment by Power-Maverick** [comment]
You will have to do a build twice one with _Managed Solution_ **unchecked** for unmanaged and another one with _Managed Solution_ **checked** to generate managed solution
