### ISSUE TITLE
Path for SolutionPackager.exe is wrong in the latest version

### ISSUE THREAD

**Issue by wnbittle** [Power-Maverick/PCF-CustomControlBuilder#26]
**Describe the bug**
Path for SolutionPackager.exe is wrong in the latest version

**To Reproduce**
1. New PCF
2. Build and add to new or existing solution
3. See error

The SolutionPackager.exe is in the %user%\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\Maverick.PCF.Builder folder, but the tool is looking for it in the C:\Users\wbittle\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\Maverick.PCF.Builder\CoreTools folder.

**Expected behavior**
The tool would find the SolutionPackager.exe to complete the packaging process

**Screenshots**
![Solution Packager Error](https://user-images.githubusercontent.com/11467997/96595897-25a94780-12ba-11eb-8026-92a34cc9d401.png)

**Desktop**
 - OS: Windows 10
 - XrmToolbox Version: 1.2020.10.41
 - PCF Custom Control Builder Version: 2.2020.10.92

**Additional context**
Manually creating the CoreTools folder and copying the appropriate files there fixes the issue and is a temporary work around.

**Comment by Power-Maverick** [comment]
I just released a new patched version resolving this issue. Thanks for bringing this to my attention.
Please test it out with version _2.2020.10.201_.

**Comment by wnbittle** [comment]
@Power-Maverick The latest update fixes this problem, thanks!
