### ISSUE TITLE
Deploy button disabled and CDS Solution Details reports Not Initialized

### ISSUE THREAD

**Issue by wnbittle** [Power-Maverick/PCF-CustomControlBuilder#27]
**Describe the bug**
I can't seem to get the Deploy button to be enabled.  Am I using the tool incorrectly or is there a bug?  Using the process outlined in the next section was working for me in prior versions.

**To Reproduce**
1. Point to the control location
1. Click the reload details button
1. Click the Build button under the PCF Component Details section
1. Assuming that succeeded, I click the Use Existing Solution checkbox
1. Select the appropriate solution
1. Click the Export and Add Control button
1. Click the Build button in the CDS Solution Details section
1. The Deploy button is still disabled and the CDS Solution Details section still reports "Not Initialized"

The control builds successfully, the solution is downloaded and extracted successfully, the control is added to the solution successfully, and the MS Build step completes successfully.

**Expected behavior**
After step 6, I would expect the CDS Solution Details section to report "Initialized".  After step 7, the deploy button should be enabled.

**Screenshots**
![deployissue](https://user-images.githubusercontent.com/11467997/96604389-0f53b980-12c3-11eb-8417-ecbd3de83a89.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - XrmToolbox Version: 1.2020.10.41
 - PCF Custom Control Builder Version: 2.2020.10.201

**Additional context**
When I select an existing solution, the Publisher Name, Prefix, and version all populate correct.  However, when I click the Export and Add Control button, it does all the commands, but then clears out the Publisher Name and Publisher Prefix fields - I'm guessing this is why it's "Not Initialized" and the Deploy button is disabled?

**Comment by Power-Maverick** [comment]
Looking at the screenshot it feels like you have not clicked on "Build" which will generate the solution files for deployment. Can you validate that you have clicked "Build" button? Thanks.

**Comment by wnbittle** [comment]
Correct.  In the screenshot I didn't include the build output, but I did click the Build button and the build succeeds.

**Comment by oiluis** [comment]
Facing the same bug here and on my case, the solution number is not updating:

![image](https://user-images.githubusercontent.com/2482647/96637578-3dea8800-12f5-11eb-86d9-61459ae7e822.png)

**Comment by Power-Maverick** [comment]
This should be resolved in version **2.2020.10.212**. I just released it.

**Comment by wnbittle** [comment]
@Power-Maverick Thanks a lot for the quick fixes - the full process defined above appears to be working again!
