### ISSUE TITLE
Find a way to support publisher names with spaces

### ISSUE THREAD

**Issue by wnbittle** [Power-Maverick/PCF-CustomControlBuilder#28]
**Is your feature request related to a problem? Please describe.**
Yes.  The current `pac` commands that include `--publisher-name` are looking for the publisher name without spaces.  This is a problem as it's very common for a publisher display name to have spaces.

![issue3](https://user-images.githubusercontent.com/11467997/96789919-f979ed80-13c3-11eb-9872-35edd0808efe.png)

**Describe the solution you'd like**
Investigation into the existing `pac` command line to understand if using single quotes, double quotes, or some other special character would allow support for publisher names with spaces.  Alternatively, if this plugin could support it via a custom pac command that does support this.

**Describe alternatives you've considered**
The current solution is to create a dummy solution with a publisher name without spaces to get the PCF control into the environment and then move it the correct solution with the correct publisher.

**Additional context**
This is an issue with the `pac` commands as far as I can tell, so this is a request to see if this tool could work around the limitation.

**Comment by Power-Maverick** [comment]
Resolved in version 2.2021.02.023
