### ISSUE TITLE
Add Release Configuration Mode

### ISSUE THREAD

**Issue by rwilson504** [Power-Maverick/PCF-CustomControlBuilder#29]
**Is your feature request related to a problem? Please describe.**
Need to reduce the size of the bundle.js files.

**Describe the solution you'd like**
I would like to be able to select Development or Release mode for the msbuild command that actually builds the component.  Currently I am using this tool to build all my components but the bundle.js files are much larger than they need to be.

```
msbuild /p:configuration=Release
```

**Describe alternatives you've considered**
I could also just use DevOps to create a pipeline for these controls to build them in release mode but it would be nice to have the option in the tool.

**Additional context**

**Comment by Power-Maverick** [comment]
Hi @rwilson504 the functionality already exists. In CDS Solution Details section, before building the CDS project, check "Managed" and then build it. This will create a production ready file which can be deployed to your environment using the "Deploy" button.

![image](https://user-images.githubusercontent.com/36135520/99407651-57afc880-28bd-11eb-8884-c08f0b89d392.png)

**Comment by rwilson504** [comment]
Perfect, thanks again for all your work on this tool!
