### ISSUE TITLE
Power Apps CLI not detected on this machine

### ISSUE THREAD

**Issue by ihocan** [Power-Maverick/PCF-CustomControlBuilder#34]
**Describe the bug**
When PCF Builder oppened this issue comes, i installed Power Apps CLI pac command are working on CMD.

**To Reproduce**
1. Power Apps CLI install
2. Open Tools on Xrm Toolbox

**Screenshots**
![image](https://user-images.githubusercontent.com/6352894/104471265-b3e84d80-55cb-11eb-86d6-f39a8bce2f94.png)
![image](https://user-images.githubusercontent.com/6352894/104471821-5acce980-55cc-11eb-82df-7de123247cd8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - XrmToolbox Version:1.2021.1.44
 - PCF Custom Control Builder Version : 2.2021.1.122
 - Power App CLI Version : 1.4.4+g0574e87

**Comment by Power-Maverick** [comment]
Did you install it after opening PCF Builder or before? Are you still getting this error?

**Comment by xvisionbelgium** [comment]
> 
> 
> Did you install it after opening PCF Builder or before? Are you still getting this error?

Hi, I'm having the same issue.

Fresh install of the Tool. Also version 1.4.4 of PowerApps CLI
pac command works on the command line and in powershell

**Comment by ihocan** [comment]
@Power-Maverick actually i found the issue, 
it's related by CheckPacVersion method in MainPluginControl.cs at line 713, code is checking the "version" text in output, but as you see in my first message output is difrrent language at my computer, it's showing "Sürüm" instant of "version".

https://github.com/Power-Maverick/PCF-CustomControlBuilder/blob/814c7244642ad72f2439bdf882aa148a1b42c37e/Maverick.PCF.Builder/MainPluginControl.cs#L713

**Comment by ihocan** [comment]
@xvisionbelgium i think pac commands showing diffrent text on your computer also, maybe local language?

**Comment by Power-Maverick** [comment]
I'll get it fixed soon. Sorry for this annoying bug. Wish there was a better way to detect if Power Apps CLI is installed on the machine other than evaluating the output of the `pac` command. Any ideas are welcomed.

**Comment by xvisionbelgium** [comment]
Hi


Probably
Mine is giving output in Dutch (local language)

PS C:\Users\JohanH.XV-JHW7-PC> pac
Microsoft PowerApps CLI
Versie: 1.4.4+g0574e87

Gebruik: pac [auth] [help] [org] [package] [pcf] [plugin] [solution] [telemetry]

  auth                        Beheren hoe u bij verschillende services verifieert
  help                        Help voor de Microsoft PowerApps CLI weergeven
  org                         Werken met uw CDS-organisatie
  package                     Opdrachten voor het werken met CDS-pakketprojecten
  pcf                         Opdrachten voor werken met PowerApps component framework-projecten
  plugin                      Opdrachten voor werken met klassebibliotheek voor CDS-invoegtoepassingen
  solution                    Opdrachten voor het werken met CDS-oplossingsprojecten
  telemetry                   Telemetrie-instellingen beheren

Launcher usage: pac [install] [use]

  install <version# | latest> Install 'latest' or a specified version of the Microsoft PowerApps CLI
  use <version# | latest>     Use 'latest' or a specified version of the Microsoft PowerApps CLI

**Comment by Power-Maverick** [comment]
Working on the fix. Will test it with a non-English machine and release the fix soon.

**Comment by Power-Maverick** [comment]
Tagging @carfup for visibility.

**Comment by ihocan** [comment]
@Power-Maverick Maybe you can use "Get-Command" with powershell it's return detail about command,  i didn't find any good script when i check for CMD.

![image](https://user-images.githubusercontent.com/6352894/106936318-7c357700-672d-11eb-95cd-86639a350df8.png)

**Comment by Power-Maverick** [comment]
@ihocan that doesn't give me the version of the CLI installed on the machine.

**Comment by Power-Maverick** [comment]
Issue is now fixed in 2.2021.02.052 version. For a non-English language I won't be able to find the CLI version but at least you should not get a prompt if CLI is installed. And if everything goes south; the tool wont force close itself.
