### ISSUE TITLE
Default UniqueName of Published To Lower Case

### ISSUE THREAD

**Issue by rwilson504** [Power-Maverick/PCF-CustomControlBuilder#35]
**Describe the solution you'd like**
Would it be possible that when creating the Solution.xml file for a PCF solution the UniqueName of the publisher get set to lowercase or you create a field on the PCF Builder for for setting the UniqueName.  

I'm asking because recently i have run into some problems with users who have installed my PCF components. The problem occurs because in my components i have always been setting my published name to RAW so the solutions that are generated have the UniqueName of 'RAW'.  The publisher though on my primary dev box where I do many of my samples to give to users for the PCF components has the UniqueNameof the publisher set to 'raw'.  When doing unmanaged solution this is not an issue but if a user has already installed on of my PCF components as a managed solution they run into an issue when one managed solution with the same Publisher but a difference in the casing of the UniqueNameis imported.

![image](https://user-images.githubusercontent.com/7444929/106357370-b3da9400-62d3-11eb-96e5-1fb5ad2d452a.png)

**Describe alternatives you've considered**
To solve my issue currently I'm going to just go into my dev box and update the publisher unique name to be upercase.

**Additional context**
Setting the unique name by default to lowercase would match what Microsoft does when you create a new publisher.  When you type in the display name they take that to remove any special characters and set it to lowercase.

![image](https://user-images.githubusercontent.com/7444929/106357499-6a3e7900-62d4-11eb-8f19-e5d96af3432a.png)

Here is an image of the Publisher name I typed into the tool and the current way the tool leaves the casing as the way i typed it in for the UniqueName.
![image](https://user-images.githubusercontent.com/7444929/106357236-e768ee80-62d2-11eb-96eb-0a5c5bd74f2e.png)

**Comment by Power-Maverick** [comment]
Resolved in version 2.2021.02.023
