### ISSUE TITLE
Issue with selecting an existing solution

### ISSUE THREAD

**Issue by wnbittle** [Power-Maverick/PCF-CustomControlBuilder#36]
**Describe the bug**
When I select from the drop down a solution file after clicking the "Use Existing Solution" checkbox, nothing shows up in the Solution Friendly Name field or (Publisher) Friendly Name field.  The Publisher Unique Name and Prefix fields DO populate.  Clicking the Export and Add Control button fails saying "Project file does not exist."

**To Reproduce**
1. Set the control location to an existing control
2. Click the reload details button
3. Click the Use Existing Solution checkbox
4. Choose a solution you have not chosen before
5. The Solution Friendly Name field remains blank and the Publisher Details - Friendly Name field is blank.  The Export and Add Control button is enabled, but when clicked reports "Project file does not exist."

**Expected behavior**
The fields mentioned before should populate and the Export and Add Control button should work properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/11467997/106775773-6894ee00-6611-11eb-95e4-7d96f8db5ed6.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - XrmToolbox Version: 1.2021.1.44
 - PCF Custom Control Builder Version: 2.2021.2.23

**Additional context**
N/A

**Comment by Power-Maverick** [comment]
Resolved in 2.2021.02.031 version

**Comment by wnbittle** [comment]
Awesome, thanks for the quick fix.  It's working now!
