### ISSUE TITLE
Terminology query Control location vs. Working folder

### ISSUE THREAD

**Issue by OliverFlint** [Power-Maverick/PCF-CustomControlBuilder#39]
Not a major issue but may want to consider making this terminology consistent...

![image](https://user-images.githubusercontent.com/8300688/106813080-70cc4800-6668-11eb-9dea-9ccba1ca9219.png)

**Comment by Power-Maverick** [comment]
Nice catch. That was a low-hanging fruit since the first release when I called _Control Location_ as _Working Folder_ but users didn't like that terminology. Will surely get this fixed in next release.

**Comment by Power-Maverick** [comment]
Issue is now fixed in 2.2021.02.052 version.
