### ISSUE TITLE
Generic error when opening tool

### ISSUE THREAD

**Issue by OOlashyn** [Power-Maverick/PCF-CustomControlBuilder#53]
**Describe the bug**
I created a control. Everything was fine until I created and built a solution. After that, on the next open of the XrmToolbox, I got this error and the tool stopped picking up details of the solution.

**Expected behavior**
The error shouldn't appear and a plugin should pick up details of the existing solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/17760686/120079266-5d2f6c00-c0b3-11eb-87da-b249cc5dc2f4.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - XrmToolbox Version 1.2021.5.42
 - PCF Custom Control Builder Version 2.2021.5.241

**Additional context**

**Comment by Power-Maverick** [comment]
Did you create a new project using the new version or opened an existing project which may have been created in older version of PCF Builder?

**Comment by OOlashyn** [comment]
I created a new project. I tested yesterday and the error just disappeared without any changes from my side. I will close the ticket now.
