### ISSUE TITLE
[Feature]: Build and deployment of "Debug" version of PCF to the "Prod" environment causes issues

### ISSUE THREAD

**Issue by lesyk** [Power-Maverick/PCF-CustomControlBuilder#56]
### Contact Details

vilesyk@microsoft.com

### Is your feature request related to a problem?

Yes

### Describe the problem?

Issue description by one of customers: https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Solution-Checker-and-PCF-Component-with-React/m-p/963736/thread-id/4627

> We are having some issues with running the solution checker on unmanaged PCF Components with React imported as a dependency.
> If i take this example and compile a solution from it, it will give 398 errors from the solution checker (mostly from the react bundle)
> https://github.com/microsoft/PowerApps-Samples/tree/master/component-framework/ReactStandardControl
> Are there any ways to ignore external libraries or maybe i am compiling this in a wrong way?
> msbuild /t:build /restore /p:configuration=Release

### Provide a solution or an idea you would like to see in the tool?

Root cause of the issue: customer uses XRMToolBox for building PCF control, where by default build builds _Debug_ version, and there is no ability (to the best of my knowledge) to build _Production_ version.

So, request here is to modify UI so that it is clear which version is build and which version will be publish to the CE environment.

We already made doc change: 
https://github.com/MicrosoftDocs/powerapps-docs/pull/2561
https://github.com/MicrosoftDocs/powerapps-docs/pull/2560

**Comment by Power-Maverick** [comment]
First of all, thank you for using the tool. I think you are not using the latest version of the tool as in the new version I have enabled the ability to choose your own “solution type” as well as “build mode”. See the screenshot below.
When you use the Build Mode = Release it should create a production version. If you are using the latest then please share more details as to what should change. Does it not create a production version even after selecting the Build Mode as Release?

![image](https://user-images.githubusercontent.com/36135520/126209793-ff1ba836-9dd1-4801-81ab-4293d0e25e18.png)

**Comment by lesyk** [comment]
Thank you so much for the fast answer.
