### ISSUE TITLE
Loading an existing PCF : Additional package selection is required

### ISSUE THREAD

**Issue by MscrmTools** [Power-Maverick/PCF-CustomControlBuilder#58]
Hi @Power-Maverick,

I was loading an existing PCF to build and push, but when loading details, I'm facing this issue:
![image](https://user-images.githubusercontent.com/10774317/151769810-2fa9fcab-87b7-44a0-bc4d-2630ee83251b.png)

But I cannot select an additional package since it's disabled.

---
- Deployment: Online
- DB Version: 9.2.21123.172
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53
- Tool Version: 2.2021.8.221

**Comment by Ale-Cesetti** [comment]
Hello @Power-Maverick 

Today I got exactly the same issue, is there any idea on why this is happening?

Since @MscrmTools is here too :) this happened to me when opening the Action Buttons PCF control which I was going to test.

Thanks!!!
Ale

**Comment by Ale-Cesetti** [comment]
It looks like that after closing and restarting the PCF Builder tool inside XrmToolBox it started working for me.

**Comment by Power-Maverick** [comment]
Fixed in version 2.2023.03.201

**Comment by SatkunamSuganthar** [comment]
Hi @Power-Maverick  I'm getting this error now with a version of v 2.2023.6.162

![image](https://github.com/Power-Maverick/PCF-CustomControlBuilder/assets/97066265/ed450f57-c2ca-4689-a0ce-33117aae1bbb)

**Comment by SatkunamSuganthar** [comment]
@Power-Maverick  Looks like as @Ale-Cesetti  suggested. close the tool and re-open solved the Issue. 

I think with an onload of the PCF, if you could set the Additional packages with None is missing initially. has it to be set to None all the time?
