### ISSUE TITLE
if i use a2b or b2b as my publisher prefix, it throws an error saying incorrect publisher.

### ISSUE THREAD

**Issue by npmModuleCIF** [Power-Maverick/PCF-CustomControlBuilder#61]
### What happened?

I found one issue, if i use a2b or b2b as my publisher prefix, it throws an error saying incorrect publisher. I look at the regex code, which needs to be modied for a2b, or b2b type of publisher prefixes. For my project i have just 3 letters middle one being the number and other two characters are alpha characters. 

### What version of the tool are you using?

1.2022.5.56

### What version of XrmToolBox are you running?

1.2022.5.56

**Comment by npmModuleCIF** [comment]
Looks like you fixed it already, can you please push an update to xrmtoolbox. I start using it. Thanks for the great tool.

**Comment by Power-Maverick** [comment]
The update is now pushed to XTB. Thanks for the reminder.

**Comment by Power-Maverick** [comment]
Was fixed in version 2.2022.07.162
