### ISSUE TITLE
[Feature]: Support for React controls & platform libraries (Preview)

### ISSUE THREAD

**Issue by JimDaly** [Power-Maverick/PCF-CustomControlBuilder#65]
### Is your feature request related to a problem?

No

### Describe the problem?

I don't see any capability to use [React controls & platform libraries (Preview)](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/react-controls-platform-libraries)

### Provide a solution or an idea you would like to see in the tool?

React controls & platform libraries (Preview) has been in preview for about a year now. 
I was looking for an option to use them with your PCF Builder. Did I miss something? Or is this planned?

**Comment by Power-Maverick** [comment]
Thanks for the reminder. Slipped my mind with other things. Should be realized this week.

Lemme know if you are open to beta test it.

**Comment by Power-Maverick** [comment]
Released a new version 2.2023.03.201.
